### ISSUE TITLE
Fully custom root path can not be defined

### ISSUE THREAD

**Issue by lrvick** [ericclemmons/grunt-angular-templates#18]
In my dev environment my views live at: app/views/*.html

My final compiled application expects the view ids to be '/views/*.html'

My config attempt here:

```
ngtmplates:
    dist:
        options:
            base: 'views/'
        src: ['app/views/**.html']
        dest: '.tmp/js/views.js'
```

I expect base to over-write the base-url of the generated ids so they are '/views/somefile.html' however it produces '../app/views/somefile.html' instead.

Any ideas of an option combination to deal with this case, or perhaps make a blanket way to hard-code my preferred full-path to the filenames in the ids?
